"""empty message

Revision ID: 171b17b4ea99
Revises: e8c3843dbd7a
Create Date: 2022-06-24 15:00:59.266274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171b17b4ea99'
down_revision = 'e8c3843dbd7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
